//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_musteri()
        {
            this.Table_satis = new HashSet<Table_satis>();
        }
    
        public int MusteriId { get; set; }

        [Required(ErrorMessage ="Bu Alanaı Boş BıRAKAMAZSINIZ....!!")]
        [StringLength(50,ErrorMessage ="En fazla 50 karakter")]
        public string MusteriAd { get; set; }
        public string müsterisoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_satis> Table_satis { get; set; }
    }
}
